/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MockERC20__factory } from "./MockERC20__factory";
export { MultiSender__factory } from "./MultiSender__factory";
